### ISSUE TITLE
IFrameBuffered

### ISSUE THREAD

**Issue by Donaut** [sbarisic/NuklearDotNet#16]
I'm trying to implement the IFrameBuffered interface (It's all good and working :D 👍 ) **My** only problem is that I need a way to trigger the whole buffering process manually. I need this because it's possible that the Buffer size is going to change at runtime.

**Comment by sbarisic** [comment]
There is `NuklearAPI.QueueForceUpdate()` and `NuklearDevice.ForceUpdate()`

First one enqueues force update to happen in next call to `NuklearAPI.Frame`, second one immediately enqueues a force update event.

**Comment by Donaut** [comment]
Looked at the source code and ForceUpdate do nothing! 
![image](https://user-images.githubusercontent.com/30203762/91753413-2aaa1e80-ebc8-11ea-92fe-9fe456c73375.png)

**Comment by sbarisic** [comment]
Yes, but if you put a print statement inside BeginBuffering, you'll see it execute every time you force update. Every time some event happens, the whole GUI redraws, so basically every time you move your mouse or press a key. That's because nuklear was not designed to be used this way, but it works fine.

**Comment by Donaut** [comment]
Ok. It's finally working the renderer is nicely written and can handle resizing.
